// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadConfig():Promise<main.Config>;

export function LoadLayout(arg1:string):Promise<Array<main.KeyLayout>>;

export function SaveConfig(arg1:main.Config):Promise<void>;
